(function () {

    angular.module('app', [
      'ngAnimate',
      'ngCookies',
      'ngResource',
      'ngSanitize',
      'ngTouch',
      'ngMessages',
      'picardy.fontawesome',
      'ui.bootstrap',
      'ui.router',
      'ui.utils',
      'angular-loading-bar',
      'angular-momentjs',
      'FBAngular',
      // 'lazyModel',
      'toastr',
      'angularBootstrapNavTree',
      'oc.lazyLoad',
      'ui.select',
      'ui.tree',
      'textAngular',
      'colorpicker.module',
      'angularFileUpload',
      'ngImgCrop',
      'datatables',
      'datatables.bootstrap',
      'datatables.colreorder',
      'datatables.colvis',
      'datatables.tabletools',
      'datatables.scroller',
      'datatables.columnfilter',
      'ui.grid',
      'ui.grid.resizeColumns',
      'ui.grid.edit',
      'ui.grid.moveColumns',
      'ngTable',
      'smart-table',
      'angular-flot',
      'angular-rickshaw',
      'easypiechart',
      'uiGmapgoogle-maps',
      'ui.calendar',
      'ngTagsInput',
      'pascalprecht.translate',
      'ngMaterial',
      'localytics.directives',
      'leaflet-directive',
      'wu.masonry',
      'ipsum',
      'angular-intro',
      'dragularModule'
    ]);

})();
